---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте удобным способом
  - Пользователь должен иметь возможность создать новую игру с возможностью выбора уровня, времени, темы игры, фильтрации тем
  - Пользователь должен иметь возможность просматривать обучение к игре
  - Пользователь должен иметь возможность выбирать язык програмирования в игре, видеть код соперника 
  - Пользователь должен иметь возможность генерировать ссылки для игры с другом
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь удобную мобильную версию
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
